#  NumPy (Numerical Python) 

### create a zeros array with given shape and datatype

In [11]:
import numpy as np
# Create a zeros

zeros = np.zeros([2,3])

print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


### create ones array with given datatype

In [20]:
var=np.ones([3,5,6,8], dtype=np.int64)
var

array([[[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1,

### Empty array creation

In [4]:
np.empty([2,4,6,8])

array([[[[ 1.19537530e-311,  1.19536832e-311,  1.82050571e-070,
           0.00000000e+000,  4.22764693e-181,  5.90408447e-321,
           3.01275004e-282,  1.96619718e-306],
         [ 2.35838901e-310,  0.00000000e+000,  0.00000000e+000,
           1.44952530e-311,  1.07444599e-296,  1.87603318e-171,
           5.74894786e-320,  8.25869269e-296],
         [ 2.22507386e-307,  1.28168548e-311,  1.22947701e-166,
           1.32624777e-310,  0.00000000e+000,  0.00000000e+000,
           1.50619992e-181,  1.19411054e-166],
         [ 2.04436186e-282,  3.71668010e-310,  4.59657611e-315,
           1.29495336e-272,  5.41313262e-291,  5.51316554e-210,
           6.25487108e-320,  1.18832073e-166],
         [ 3.55682967e-286,  1.39067116e-309,  3.93349935e-315,
           6.72378229e-239,  3.04049085e-316,  1.08217597e-282,
           7.78665516e-162,  1.10825078e-301],
         [ 5.09399615e-315,  1.29748064e-272,  2.76481388e-176,
           2.02369350e-315,  0.00000000e+000,  1.29396333e-27

### create Arrange array

In [14]:
arrange=np.arange(0,10,2)
arrange

array([0, 2, 4, 6, 8])

### create linspace array

In [16]:
linespace=np.linspace(0,10,6100)
linespace

array([ 0.        ,  0.16949153,  0.33898305,  0.50847458,  0.6779661 ,
        0.84745763,  1.01694915,  1.18644068,  1.3559322 ,  1.52542373,
        1.69491525,  1.86440678,  2.03389831,  2.20338983,  2.37288136,
        2.54237288,  2.71186441,  2.88135593,  3.05084746,  3.22033898,
        3.38983051,  3.55932203,  3.72881356,  3.89830508,  4.06779661,
        4.23728814,  4.40677966,  4.57627119,  4.74576271,  4.91525424,
        5.08474576,  5.25423729,  5.42372881,  5.59322034,  5.76271186,
        5.93220339,  6.10169492,  6.27118644,  6.44067797,  6.61016949,
        6.77966102,  6.94915254,  7.11864407,  7.28813559,  7.45762712,
        7.62711864,  7.79661017,  7.96610169,  8.13559322,  8.30508475,
        8.47457627,  8.6440678 ,  8.81355932,  8.98305085,  9.15254237,
        9.3220339 ,  9.49152542,  9.66101695,  9.83050847, 10.        ])

### How to Sort the array

In [7]:
arr=[1, 4, 2, 5, 3, 6, 8, 9, 7, 10]
np.sort(arr, kind='quicksort')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### argsort array index

In [8]:
np.argsort(arr)

array([0, 2, 4, 1, 3, 5, 8, 6, 7, 9])

In [ ]:
### Generate an empty 4 dimensional array fill elements in it using for loop

arr_4d = np.empty((4, 4, 4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            for l in range(4):
                arr_4d[i, j, k, l] = i * 1000 + j * 100 + k * 10 + l
                print(arr_4d)


[[[[  0. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]]


 [[[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]]


 [[[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   

In [17]:
# identity function
arr_identity = np.identity(3)
print(arr_identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr_identity1 = np.eye(3)
print(arr_identity1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
