#  NumPy (Numerical Python) 

### create a zeros array with given shape and datatype

In [2]:
import numpy as np
# Create a zeros

zeros = np.zeros([2,3])

print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


### create ones array with given datatype

In [3]:
var=np.ones([3,5,6,8], dtype=np.int64)
var

array([[[[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1],
         [1,

### Empty array creation

In [4]:
np.empty([2,4,6,8])

array([[[[ 1.39276025e-311,  1.39274914e-311,  7.58359892e-309,
           3.91910665e+202,  5.92878775e-323,  0.00000000e+000,
           4.03776824e+202,  3.95252517e-323],
         [ 0.00000000e+000,  2.31964693e-309,  4.21560924e+149,
           3.45845952e-323,  2.25170697e+289,  4.66714172e-318,
           0.00000000e+000,  1.32031261e-019],
         [ 6.45696231e+067,  1.61192838e+020,  2.43861180e-152,
           2.44001263e-152,  5.81241632e+180,  6.25648973e-085,
           1.33360353e+241,  3.22925319e-310],
         [-8.10647934e+016,  1.07044741e-312,  4.68378047e-305,
           1.05628749e-309,  3.13995248e+185,  6.05713752e-312,
           7.57807137e-309,  5.37625007e+241],
         [ 2.54066628e+151,  4.81127985e+151,  2.30227740e-070,
           9.75772002e+199,  7.69417367e-309,  2.84809454e-306,
          -4.65308539e-191,  1.31016033e-251],
         [ 1.90637932e-173,  5.81177764e-247,  1.39054323e-180,
           8.09504789e-217,  3.82100374e+176,  4.25857833e-13

### create Arrange array

In [6]:
arrange=np.arange(1,10,2)
arrange

array([1, 3, 5, 7, 9])

### create linspace array

In [16]:
linespace=np.linspace(0,10,6100)
linespace

array([ 0.        ,  0.16949153,  0.33898305,  0.50847458,  0.6779661 ,
        0.84745763,  1.01694915,  1.18644068,  1.3559322 ,  1.52542373,
        1.69491525,  1.86440678,  2.03389831,  2.20338983,  2.37288136,
        2.54237288,  2.71186441,  2.88135593,  3.05084746,  3.22033898,
        3.38983051,  3.55932203,  3.72881356,  3.89830508,  4.06779661,
        4.23728814,  4.40677966,  4.57627119,  4.74576271,  4.91525424,
        5.08474576,  5.25423729,  5.42372881,  5.59322034,  5.76271186,
        5.93220339,  6.10169492,  6.27118644,  6.44067797,  6.61016949,
        6.77966102,  6.94915254,  7.11864407,  7.28813559,  7.45762712,
        7.62711864,  7.79661017,  7.96610169,  8.13559322,  8.30508475,
        8.47457627,  8.6440678 ,  8.81355932,  8.98305085,  9.15254237,
        9.3220339 ,  9.49152542,  9.66101695,  9.83050847, 10.        ])

### How to Sort the array

In [7]:
arr=[1, 4, 2, 5, 3, 6, 8, 9, 7, 10]
np.sort(arr, kind='quicksort')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### argsort array index

In [8]:
np.argsort(arr)

array([0, 2, 4, 1, 3, 5, 8, 6, 7, 9])

In [ ]:
### Generate an empty 4 dimensional array fill elements in it using for loop

arr_4d = np.empty((4, 4, 4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            for l in range(4):
                arr_4d[i, j, k, l] = i * 1000 + j * 100 + k * 10 + l
                print(arr_4d)


[[[[  0. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]]


 [[[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]]


 [[[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]]

  [[100. 100. 100. 100.]
   [100. 100. 100. 100.]
   [100. 100. 100. 100.]
   

In [17]:
# identity function
arr_identity = np.identity(3)
print(arr_identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr_identity1 = np.eye(3)
print(arr_identity1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
