# NumPy (Numerical Python)

In [7]:
import numpy as np

In [8]:
# craete 1D Numpy
num=np.arange(10,21,1)

print("Demension: ", num.ndim)
print(num)


Demension:  1
[10 11 12 13 14 15 16 17 18 19 20]


In [9]:
# exact first three elemets

#print(num[0:3])
num[0:3]


array([10, 11, 12])

In [10]:
#modfiy the last elememts to be 100 

num[9]=100
print(num)

[ 10  11  12  13  14  15  16  17  18 100  20]


In [ ]:
# craete 1D Array from 1 to 10 and exteact a slice
num1=np.array([1,2,3,4,5,6,7,8,9,10])
#extract=num1[1:11:2] 
print(num1[1:11:2])

[ 2  4  6  8 10]


In [22]:
# change the element in the slice and check the if the original array is also affected
num1[2]=10
print(num1)
print(num1)

[ 1  2 10  4  5  6  7  8  9 10]
[ 1  2 10  4  5  6  7  8  9 10]


In [13]:
# multidim
num3=np.array([[1,2,3],[4,5,6],[7,8,9]])

num3



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# retrive the elemnts from 

num3[1,2]

np.int64(6)

In [16]:
#extract the second 1d array
num3[1,1]

np.int64(5)

In [17]:
# create the 4x2 array of random integers

num4=np.random.randint(100, size=(4,2))
num4

array([[96, 63],
       [59, 68],
       [84, 53],
       [90, 58]], dtype=int32)

In [47]:
print(num4.shape)
print(num4.size)
print(num4.ndim)

(4, 2)
8
2


In [9]:
# create 1d array of 5 zeors

num5=np.zeros(5)
print(num5)
#num5.astype(int)


[0. 0. 0. 0. 0.]


In [98]:
num6=np.identity(3)
num6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
num17=np.eye(3)
num17

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#create an array of 10 evenly spaced numbers between 0 to 100
num7=np.linspace(0,100,10)
num7

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
num8=np.array([8,2,5,1,7])
np.sort(num8)


array([1, 2, 5, 7, 8])

In [71]:
num9=np.array([1,2,3])
num10=np.array([4,5,6])
sum=np.concatenate((num9,num10))
sum


array([1, 2, 3, 4, 5, 6])

In [80]:
num11=np.array([1,2,3,4,5,6])
num11.reshape((2,3))


array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
# convert the 1D array  vector
num12=np.array([1,2,3,4,5,6])
s=num12[:,np.newaxis]
s

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [85]:
num13=np.array([1,2,3,4,5])
np.expand_dims(num13, axis=0)

array([[1, 2, 3, 4, 5]])